steps:
  - bash: |
      source $HOME/.poetry/env
      poetry run pytest --cov=enturclient --cov-report=xml --cov-report=html --junitxml=junit/test-results.xml
    displayName: Tests
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: Publish test results
    inputs:
      testResultsFiles: "**/test-*.xml"
      testRunTitle: Test results
  - task: PublishCodeCoverageResults@1
    displayName: Publish coverage results
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage.xml"
