pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/init-step.yaml
  - bash: |
      source $HOME/.poetry/env
      poetry run black . --check --diff
    displayName: black check
  - bash: |
      source $HOME/.poetry/env
      poetry run pytest --cov=enturclient
    displayName: tests
  - bash: |
      source $HOME/.poetry/env
      poetry run isort --check-only
    displayName: import sorting
  - bash: |
      source $HOME/.poetry/env
      poetry run pylint enturclient
    displayName: linting
  - bash: |
      source $HOME/.poetry/env
      poetry run mypy enturclient --ignore-missing-imports --follow-imports=silent --warn-redundant-casts --warn-unused-configs --strict-equality
    displayName: typing checks
